### PR TITLE
img.ly

### PR DESCRIPTION
**Pull request by sebastiandeutsch**
Hi,

we pivoted since Twitter destroyed our initial business model. Maybe interesting for your list.

Best

Sebastian

### CODE REVIEW

**Comment by fikrikarim** [comment]
Hi @sebastiandeutsch, thanks for the PR! I looked a bit about img.ly and it's pretty inspiring!

To be honest, right now I'm not entirely sure whether to make the list only include household name companies, or whether to include all companies. But then again, who decides which company is a household company or not.

I'm still reading the HN threads to see which one people prefer. I'll merge this PR if I think it's better to include all companies. Thanks!

**Comment by sebastiandeutsch** [comment]
Understood. Thanks for your feedback.

**Comment by fikrikarim** [comment]
Hey @sebastiandeutsch, sorry for the wait. I think this should be a good addition to the list and we should be able to merge this.

One thing though, right now all the logo have maximum width of 128px. Could you update the img.ly logo width to be 128px?

Once rebased, then it should be good to go.

**Comment by sebastiandeutsch** [comment]
Happy new year! I've changed to image width to 128px and rebase to your master. Should be good to merge.

**Comment by fikrikarim** [comment]
Merged! Happy new year to you too!

**Pull request merged**
