### PR TITLE
Add elvah

### PR DESCRIPTION
**Pull request by jeromegamez**
Hey there,

I'm a member of [elvah](https://www.elvah.de/), a company that wants to excite and accelerate the adoption of sustainable mobility - our first step towards this is to provide a unified experience when charging electric vehicles with our app and flat-rate, but we have more coming up 😅.

We've been working on and as elvah since the middle of 2020, after eight years of being a successful software agency with some renowned customers in the media, sports, and travel industry. Like many others, the current pandemic hit us hard and we were faced with the choice to either shut down the company or find a solution to sustain ourselves. We preferred the latter and to take the opportunity to not "just" give our best to customers, but to put our energy into something of our own 🥰.

One of our founders, Gowry, [has created an article series on Medium describing our process to pivot to the product company we are today](https://medium.com/@gowry/how-covid-19-forced-us-to-follow-our-dreams-5c1db7d660a4), and we're happy to have [convinced a number of angel investors](https://www.startbase.com/news/elvah-sammelt-32-millionen-euro-ein/) with more financing rounds to follow 🥳.

Cheers
Jérôme

### CODE REVIEW

**Comment by fikrikarim** [comment]
Hey @jeromegamez, thanks for the submission!

A couple of things:
- Could you resize the image width to be 128px? I looked at the change and it seems that it doesn't matter much but all the logo right now have maximum dimension of 128px so it would be nice to make it the same.
- Could you shorten the description of the `Now` and `Early days` column a bit? We're trying to make it concise and easy to understand when you just skim the repo.
- I just merged a PR, so we need to rebase this PR.

Other than that, it looks good and we should be able to merge this.

**Comment by jeromegamez** [comment]
Thank you, @fikrikarim! The image is now resized, the now and early days shortened and the branch rebased 💪 🙏

**Comment by fikrikarim** [comment]
Thanks, merged!

**Comment by jeromegamez** [comment]
Thank you! 🌺

**Pull request merged**
